### ISSUE TITLE
Issue with capitalization

### ISSUE THREAD

**Issue by mdcb** [tpope/vim-abolish#101]
This could a new feature rather than an issue (but lead to some chaos...)
I couldn't find information in the documentation. Excellent plugin btw.

Given as input:
```
vimAbolish
VimAbolish
vimabolish
VIMABOLISH
```
the command `%S/vima/hello/g` produces:
```
vimAbolish
VimAbolish
hellobolish
HELLOBOLISH
```
when I would have expected:
```
hellObolish
HellObolish
hellobolish
HELLOBOLISH
```

**Comment by tpope** [comment]
What should happen to all these?

```
viMAbolish
vIMAbolish
Vimabolish
VimAbolish
ViMAbolish
VIMabolish
```

**Comment by mbec-lbto** [comment]
I would vote for: match the `dest` capitalization.
```
viMAbolish -> heLLObolish
etc.
```

**Comment by tpope** [comment]
Why is it `heLLObolish` and not `helLObolish`? You can't just say "match the capitalization" when you're going from 4 letters to 5 letters.

**Comment by mdcb** [comment]
Right, there's no good answer if the lengths don't match.
For my use case, I found out this worked:

`%S/vimA/hellO/g`
