### ISSUE TITLE
Can you update readme.md to include installation for vim8's new plugin manager.

### ISSUE THREAD

**Issue by dogunbound** [tpope/vim-abolish#105]
It would just be easier for people down the road if you could do this. vim8 plugin manager is the way of the future at this point.

**Comment by OliverChao** [comment]
You can try vim-plug plugin manager. You just add the Plug 'tpope/vim-abolish' to its plugin area, and reopen the .vimrc or init.vim(neovim)  and run :PluginInstall. It will automanticly install any plugins you need.
