### ISSUE TITLE
Option to disable one or more "child" plugins

### ISSUE THREAD

**Issue by openjck** [tpope/vim-abolish#106]
Thanks for all of the great plugins!

I try to keep my Vim configuration pretty minimal, not installing or configuring anything that I'm unlikely to use, so as to avoid becoming confused by the editor behaving unexpectedly.

As you say in the README, abolish brings together three superficially unrelated plugins. I love the substitution plugin, but I'm not sure I'd use the abbreviation or coercion plugins. It's easy enough to avoid accidentally triggering the former, but a bit harder with the latter, as it adds new keybindings.

What do you think about an option to disable one or more child plugins? This would allow a user to, for instance, disable the abbreviation and coercion plugins but leave the substitution plugin enabled.

**Comment by tpope** [comment]
There's `g:abolish_no_mappings` if you really must disable it. I'm very much of the position that there's no practical reason to bother.
