### ISSUE TITLE
Pascal case comand

### ISSUE THREAD

**Issue by nickeb96** [tpope/vim-abolish#116]
Could we add a `crp` command as an alias for `crm`?

I think `p` for pascal is more intuitive for people that were taught "NamesLikeThis" are pascal cased.  I haven't personally heard of mixed case before finding this plugin.

I saw that there are multiple commands for kebab case and snake case, so having `crp` along with `crm` shouldn't cause any conflicts.

**Comment by tpope** [comment]
FINE
