### ISSUE TITLE
Using hyphen with Abolish

### ISSUE THREAD

**Issue by MahbubAlam231** [tpope/vim-abolish#120]
I wanted to add an abbreviation similar to this:
```
Abolish fc first-countable
```
It works fine if I input `fc` or `FC`, but when I input `Fc` (for instance at the beginning of a sentence), it expands to `FirstCountable`, with no hyphen(-) and the letter next to the intended hyphen gets capitalized (I get a MixedCase word). Is there a way to write the Abolish command so that `Fc` expands into `First-countable`?

**Comment by tpope** [comment]
Not directly through `Abolish`, but you can `abbrev Fc First-countable` afterwards to override it.
