### ISSUE TITLE
Problem when using the c flag to confirm a Substitution

### ISSUE THREAD

**Issue by kurkale6ka** [tpope/vim-abolish#42]
Hi,
When using `:S/old/new/c`, this is the prompt I get:
`replace with \=Abolished() (y/n/a/q/l/^E/^Y)?`
Regards

**Comment by tpope** [comment]
What's the problem?

**Comment by kurkale6ka** [comment]
Isn't `\=Abolished()` supposed to be parsed? And show `new` for instance?

**Comment by tpope** [comment]
No, Vim doesn't support that.
