### ISSUE TITLE
Error with clipboard=unnamedplus

### ISSUE THREAD

**Issue by eugen0329** [tpope/vim-abolish#46]
I find very useful both abolish-coersion and unnamedplus clipboard (because I'm tired to take care about paste/nopaste modes), but unfortunately coersion don't work with this option. Is there a way how to fix it?

**Comment by eugen0329** [comment]
Tried to fix own hand and would like to offer to save and restore clipboard option value in a function! s:coerce(transformation), but just now discovered this commit 40ac6db. So the main problem were in my plugin manager which installs only release versions=|

**Comment by tpope** [comment]
Just cut a release. I do try to do regular releases though on more dormant projects the years go by fast.
