### ISSUE TITLE
Abbreviations disappear after changing file

### ISSUE THREAD

**Issue by MatthiasKauer** [tpope/vim-abolish#48]
Hi,
I'm observing that the abbreviations that I defined with your plugin disappear after changing the file that I edit.
I have tracked it down to the following situation (15s video: http://gfycat.com/BonySmugIchthyostega )

I open a file, abbreviations are there, I change directory, open another file, abbreviations are gone.

Abbrevs are defined in .vim/after/plugin/abolish.vim, as recommended.
The config I'm testing with here is still fairly large and I haven't had time to test with a minimal one. I'll do that in a moment, however.

Do you have a gut feeling for what is causing this? My initial feeling was that it came from filetypes, but my investigations in that direction didn't really confirm that.

Best regards,
Matthias

**Comment by MatthiasKauer** [comment]
Ok, double-checked this with minimal config now:
```
let path='~/.vim/junegunn-plugs'
call plug#begin(path)
Plug 'tpope/vim-abolish'
call plug#end()
```
plus the abolish.vim in after/plugin/
```
Abolish -buffer teh the
```
Ok, removing -buffer removes this behavior. I'll go read the manual :/

**Comment by tpope** [comment]
`-buffer` (surprise surprise) defines the abbreviation in one buffer.

**Comment by MatthiasKauer** [comment]
it's obvious to me now, but I didn't even check there at first.
Sorry for causing trouble.
