### ISSUE TITLE
Unable to use or escape special characters in expression.

### ISSUE THREAD

**Issue by dwayneyuen** [tpope/vim-abolish#51]
Say I have a list of items like so:

```
+ item 1
- item 2
```

and I want this:

```
* item 1
* item2 
```

I want to do something like `S/{-,+}/*` but the `+` gets treated like a special character. I haven't been able to make it work with any combination of backslashes before the `+` character.

This is the error message:

```
E866: (NFA regexp) Misplaced +
E64: + follows nothing
E476: Invalid command
```

Thank you for the wonderful plugin!

**Comment by Champitoad** [comment]
I'm having the same problem, seems like + is interpreted as a special character for regexps, therefore it can't be searched/replaced like you normally would with standard Vim search/replace.

**Comment by Champitoad** [comment]
OK so I looked upon Issue #24, just added + in the escape regex characters as done in [commit 3f60287](https://github.com/tpope/vim-abolish/commit/3f602873e63ae472b6130c13b928eebc322d54cb), and now it works! Going for the pull request :-)
