### ISSUE TITLE
This plugin is awesome.

### ISSUE THREAD

**Issue by sfinktah** [tpope/vim-abolish#58]
And FTR, I honestly think seperate is the correct spelling every time I type it, and I cannot blame my fingers.

I'm not too hot on disparate either, but that one isn't high on my usage list.

Keep up the good work, you're practically a house-hold name...  if you specify that only houses that contain vim users.

I found this plugin from your rails plugin, so the whole **seperate** **separate** thing is a total bonus.

**Comment by tpope** [comment]
Thanks!
