### ISSUE TITLE
Problems with search and replace

### ISSUE THREAD

**Issue by samstickland** [tpope/vim-abolish#60]
Hi,

I've just installed abolish, but it doesn't seem to be working right.

This command: `:S/sow/assignment/g` only replaces the first occurrence, it doesn't replace globally.

This command: `:S/sow/assignment/gc` gives this error message `E486: Pattern not found: \v\C%(SOW|Sow|sow)`

I hope you can help me out because I have a *lot* of search and replace to do and this tool looks awesome!

**Comment by NasaGeek** [comment]
Just like with :s, you'll need to specify some sort of range (like %) before the S to get Subvert to run on more than just the current line.

**Comment by VarunBatraIT** [comment]
Example

:%100Subvert/sow/assignment/g

**Comment by tpope** [comment]
`:%S/.../.../g` is the usual idiom.
