### ISSUE TITLE
Coerce mode from dash case not working

### ISSUE THREAD

**Issue by arcseldon** [tpope/vim-abolish#64]
This is an awesome plugin, and I use the coercions all the time, in particular camel case to snake case and vice versa. Noticed today that when already in dash case (eg. `this-is-in-dash-case`), the commands to get out of that case don't work. The other way around does work, so I can successfully convert snake or camel case into dash case.  Any ideas?  

Other coercions still work elsewhere, and `:messages` gives no indication of an issue.
`map cr-` indicates   `n cr   Coerce`

Thanks to anyone if you can offer some ideas. When naming node.js git repos it would be useful to take the name out of package.json then convert from dash case to title case directly. Atm, i have to do a `:s/-/_/g` and then now with a working coercion, do a `crt` into title case.

Am using neovim..

**Comment by tpope** [comment]
Coercion has always used Vim's definition of a word, `'iskeyword'`, so this won't work except in file types that explicitly redefine words to include dashes (e.g., Lisp). I can't think of a good way to change this without breaking other edge cases.

**Comment by arcseldon** [comment]
Tim, thanks so much for the prompt reply and explanation. All good.  Also wanted to take the opportunity to personally thank you for writing about 50% of the plugins I use :)
