### ISSUE TITLE
Why does Abolish use \k?

### ISSUE THREAD

**Issue by tandrewnichols** [tpope/vim-abolish#69]
I'm getting "E474: Invalid argument (not a keyword: [thing])" for the following:

`Abolish from-control form-control`

I understand WHY. [These lines](https://github.com/tpope/vim-abolish/blob/b6a8b49e2173ba5a1b34d00e68e0ed8addac3ebd/plugin/abolish.vim#L529-L530) check that the "bad" item matches only keyword characters and for most filetypes `-` is not part of `isk`. What I don't understand is why that's necessary. Is Abolish only intended to replace keywords (var, let, function, etc.)? Or is that a limitation of `:abbrev`? Because it seems like you might want to replace abbreviations in, for example, code comments or strings, which could be anything.

I don't think this is a _bug_ cause I can just do

```vim
augroup AbolishByFiletype
  au!
  au FileType html,css setlocal isk+=45
augroup END
```

and it works. I'm just wondering why the check for `'^\k\+$'` is necessary.

**Comment by lacygoill** [comment]
I don't know much about the plugin's code, but according to `:h abbreviations`, Vim recognizes only 3 types of abbreviations: `full-id`, `end-id`, `non-id`.

It seems the lines you linked check whether the abbreviations belong to the type `full-id`.
I don't know whether it would be possible/make sense to check for the other types, but there seems to be limitations to what `:abbrev` can be passed as first argument.

**Comment by tpope** [comment]
It's an `:abbrev` limitation.
