### ISSUE TITLE
Support Abolish RHS containing only braces

### ISSUE THREAD

**Issue by wincent** [tpope/vim-abolish#73]
Would be nice to combine two separate `:Abolish` calls like these:

```
Abolish hte the
Abolish teh the
```

Into one:

```
Abolish {hte,teh} the
```

But Vim will complain about a RHS that contains only braces:

```
E474: Invalid argument (not a keyword: '{hte,teh}')
```

This is of course such a simple case that it may not really be what Abolish is intended for (you can just use raw `:iabbrev` for cases like this), but it might be nice to add some special casing to detect RHS like this and desugar them into separate calls.

**Comment by tpope** [comment]
Just a simple edge case that got overlooked.
