### ISSUE TITLE
Request: Visual mode support for changing case/case coercion

### ISSUE THREAD

**Issue by dylan-chong** [tpope/vim-abolish#74]
Without being able to use visual mode, it is not possible to change from a "natural" case like `hello world` into a snake case `hello_world`. Pressing `crs` with the `hello world` selected will replace `hello world`  with `rs`.

**Comment by rawaludin** [comment]
This. I have same problem. My current temporary solution was to block the text, then replace space with dash on selected text, then do coercion.

Eg. ` ` = cursor position

`m`y hello world text

`wvee`
my `hello world` text

type `:`, then command will be filled with `:'<,'>`
Then complete it with `:'<,'>s/\%V /_/g` to replace space with underscore only on the pattern, not the whole line.

block the text again and do coercion.

**Comment by tpope** [comment]
There are no good visual mode maps available, but a `<Plug>` map is easy enough to provide.

**Comment by kiryph** [comment]
There is also the plugin https://github.com/arthurxavierx/vim-caser. It uses a different set of maps prefixed with `gs` instead of `cr`. This overwrites the builtin `[N]gs – Do nothing for [N] seconds`. Furthermore, 

> all mappings [...] must be followed by a motion or a text object, or be applied within visual mode.
