### ISSUE TITLE
Allow no trailing slash

### ISSUE THREAD

**Issue by tbodt** [tpope/vim-abolish#77]
:s doesn't require a trailing slash, but if you forget a trailing slash on a Subvert command, it seems to do nothing. I have gdefault set, so I usually don't need a /g on the end of patterns, so there's usually no reason for me to type a trailing slash.

**Comment by tpope** [comment]
If you omit the second trailing slash, [a search is performed instead](https://github.com/tpope/vim-abolish/blob/b95463a1cffd8fc9aff2a1ff0ae9327944948699/doc/abolish.txt#L91-L94). It's a decision I made 11 years ago, I'm afraid you're stuck with it.
