### ISSUE TITLE
coerce operator 

### ISSUE THREAD

**Issue by j-blasco** [tpope/vim-abolish#81]
Currently the coerce functionality is not working as expected. I have for example the following text:

'one-two-three'

If we would have a coerce operator we could do something like: crsiW:
cr: coerce
s: to snake case
iW: in Word

if I do, crs, it just fails detecting that I want to be able to do this within the Word. I think this functionality could be very powerful, and the plugin seems to be very close. I wonder what would be the best approach to implement this. Thank you in advance for any advice and guidance

**Comment by tpope** [comment]
The behavior you want is on `<Plug>(abolish-coerce)`. It's not mapped by default.

**Comment by blasco** [comment]
I've mapped it to:
```
map cr <Plug>(abolish-coerce)
```
![Screenshot_2019-10-07_23-26-40](https://user-images.githubusercontent.com/3214400/66349784-f13a4600-e959-11e9-8ba9-24a33ba74192.png)

But the other mapping takes preference. Is there a way to disable the other mappings?
