### ISSUE TITLE
Failing to replace words on same line

### ISSUE THREAD

**Issue by sQVe** [tpope/vim-abolish#82]
Hey :wave:,

I'm seeing an issue, compared to `substitute`, when trying to replace words on the same line. Say I have a text file with the following content:

```
foo foo Foo FOO
foo foo Foo FOO
```

If I run `:%s /foo/bar/g` it will turn into:

```
bar bar Foo FOO
bar bar Foo FOO
```

If I run `:%Subvert /foo/bar/g` it will turn into:

```
bar foo Foo FOO
bar foo Foo FOO
```

It seems like `Subvert` isn't taking the `g` flag into consideration.

I would assume that running `:%Subvert /foo/bar/g` would give the following result:

```
bar bar Bar BAR
bar bar Bar BAR
```

**Comment by tpope** [comment]
`g` is supported and is indeed giving me the 8 substitution result for your example.

**Comment by sQVe** [comment]
@tpope Does `vim-abolish` take `gdefault` in consideration? I might actually be turning the g flag off if it does... 🤣

I'll test what result I get later without.

**Comment by tpope** [comment]
It ignores `gdefault`, which means `:S` and `:s` should behave identically (but I haven't done any testing in this area).

**Comment by sQVe** [comment]
@tpope It seems like it does take `gdefault` into consideration. Omitting the `g` flag with `gdefault` or adding the `g` flag with `nogdefault` results in the intended behavior.

**Comment by sQVe** [comment]
Closing this issue as I got my answer but it might be worth noting that the plugin follows the `gdefault` setting.
