### ISSUE TITLE
Abolish substitutions are not applied unless followed by a space.

### ISSUE THREAD

**Issue by jonhiggs** [tpope/vim-abolish#83]
Abolish substitutions are not applied unless followed by a space.

```
a line ending with seperate
a sentence ending with seperate
and separate in the middle of the sentence.
this seperate; that seperate.
```

**Comment by tpope** [comment]
I assume from your example text you mean abbreviations and not the actual `:substitute` functionality. A `<CR>` map could interfere with the end of the line abbreviations and a nonstandard `'iskeyword'` could interfere when there's subsequent punctuation.

**Comment by jonhiggs** [comment]
Yeah, sorry. This is the rule.
```
Abolish sep{a,e}rat{e,ely,ed,ing,ion,or} sep{a}rat{}
```

Thank you for the suggestion. I reset iskeyword to the default (`@,48-57,_,192-255`), however that has not solved the problem.

**Comment by tpope** [comment]
What about `:verbose imap <CR>`?

**Comment by jonhiggs** [comment]
Thank you so much. I doubt I'd had ever found that. It was set by vim-pencil. Turning `:PencilOff` solved the the problem for me.
