### ISSUE TITLE
:Subvert doesn't support incremental search and highlight all matches

### ISSUE THREAD

**Issue by ppg** [tpope/vim-abolish#84]
I have [incremental search](https://vimhelp.org/options.txt.html#%27incsearch%27) and [highlight all matches](https://vimhelp.org/options.txt.html#%27hlsearch%27) turned on in my vim setup, which means when I would do type a command like `:s/` and start typing it will highlight the matches as I type. I like the preserve case functionality of `:S/` but would like it to incrementally highlight the matches as I type too.

**Comment by zlksnk** [comment]
[A plugin that can solve it](https://github.com/markonm/traces.vim/issues/41#issuecomment-774324994) till then.

**Comment by tpope** [comment]
That's pretty cool! It looks pretty heavyweight so I'm gonna assume this isn't something I should bring in-house, but I welcome other opinions on the subject.
