### ISSUE TITLE
Can I use coercion functions in my own vimscript functions?

### ISSUE THREAD

**Issue by TheLudd** [tpope/vim-abolish#90]
I realize this may be more of a general vimscript question but I would like to write my own functions where I use coercion logic, such as always converting the input to dash case.

A function to do that is ofc already defined in this plugin [here](https://github.com/tpope/vim-abolish/blob/master/plugin/abolish.vim#L133). 

Is it possible for me to "import" and reuse this and other functions defined in the abolish plugin?

**Comment by tpope** [comment]
It's available as `g:Abolish.dashcase()`.
