### ISSUE TITLE
Feature Request: Coerce Kebab Case

### ISSUE THREAD

**Issue by atomdmac** [tpope/vim-abolish#92]
I'm guessing this is easier said than done but it would be need to have a `crk` command for converting to `kebab-case`.  Curious to know if it's been considered already or if others would find it useful.

**Comment by joechrisellis** [comment]
I believe you can already do this with `cr-`! 🙂

**Comment by atomdmac** [comment]
So you can!  I totally missed that.  (The only downside is that it looks like kebab-case items can't be converted to any other cases :( ).  Still, the existing functionality is way better than nothing.  Thanks for pointing this out!
