### ISSUE TITLE
Doesn't work with parens?

### ISSUE THREAD

**Issue by LandonSchropp** [tpope/vim-abolish#96]
Sorry if this is a dumb question, but I can't seem to get Abolish to work with parens.

Here's my config:

```
Abolish descirbe describe
```

This works if I type `descirbe `, but not if I type `descirbe(`. Is there a trick I'm missing to get this to work with function calls?

Thanks!

**Comment by tpope** [comment]
Check `:verbose set iskeyword?`. The behavior seeing sounds like parentheses made it in there somehow.

**Comment by LandonSchropp** [comment]
That was the problem! Thanks for the help. 🙂
