### ISSUE TITLE
Error adding elipsis instead of three dots

### ISSUE THREAD

**Issue by lyz-code** [tpope/vim-abolish#99]
I would like for abolish to change the three dots `...` for the elipsis symbol `…`, but I encounter two errors:

* Abolish complains that `...` is not a keyword: `Invalid argument (not a keyword: '...')`
* As it's attached to the end of a word, it may not even be possible to do so.

Do you think it's doable?

Thanks :)

**Comment by tpope** [comment]
Abolish can only do what `:abbrev` can do, so no, I don't think it is possible.
